### ISSUE TITLE
The github.com/pornel/zopfli does not exist anymore

### ISSUE THREAD

**Issue by ruslansagitov** [eGavr/image-optim#42]
The setup fails because of https://github.com/bem-archive/image-optim/blob/aaac321cf4000495ac52214833a905fd4d7ee9e5/env/env-setup#L12

**Comment by theted** [comment]
There is a [pornel/google-zopfli](https://github.com/pornel/google-zopfli) repo, so I thought that it had simply been renamed. However when testing (using the latest commit) I get patching errors, so this is clearly not the correct repo. I also found [ImageOptim/zopfli](https://github.com/ImageOptim/zopfli), which is maintained by the same author, contains the correct commit (https://github.com/ImageOptim/zopfli/commit/0726c038cd3cdc788f3e8dfd33664bb999baaa59), and installs successfully. Submitting a pull request shortly.

**Comment by Jorenm** [comment]
Any chance this pull request is ever getting accepted? It definitely fixes the issue.

**Comment by ruslansagitov** [comment]
@eGavr A new version?

**Comment by eGavr** [comment]
Done.

`0.4.2`
